version: '3.9'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: racfella-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: racfella
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in your environment}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - racfella-internal

  redis:
    image: redis:7-alpine
    container_name: racfella-redis
    restart: unless-stopped
    command: redis-server --appendonly yes ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - racfella-internal

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: racfella-agent:latest
    container_name: racfella-agent
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/racfella
      REDIS_URL: redis://${REDIS_PASSWORD:+:$REDIS_PASSWORD@}redis:6379
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:?Set OPENROUTER_API_KEY in your environment}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      MORALIS_API_KEY: ${MORALIS_API_KEY:-}
      ADVANCED_MODEL: ${ADVANCED_MODEL:-gpt-4-turbo-preview}
      UTILITY_MODEL: ${UTILITY_MODEL:-gpt-3.5-turbo}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-text-embedding-ada-002}
      AES_ENCRYPTION_KEY: ${AES_ENCRYPTION_KEY:?Set AES_ENCRYPTION_KEY in your environment}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:?Set TWILIO_ACCOUNT_SID in your environment}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:?Set TWILIO_AUTH_TOKEN in your environment}
      TWILIO_WHATSAPP_FROM: ${TWILIO_WHATSAPP_FROM:?Set TWILIO_WHATSAPP_FROM in your environment}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY:-}
      APP_BASE_URL: ${APP_BASE_URL}
      PORT: 3000
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-https://racfella-agent.racfathers.io}
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # HTTP Router (redirects to HTTPS)
      - traefik.http.routers.racfella-agent-http.rule=Host(`racfella-agent.racfathers.io`)
      - traefik.http.routers.racfella-agent-http.entrypoints=web
      - traefik.http.routers.racfella-agent-http.middlewares=https-redirect
      # HTTPS Router
      - traefik.http.routers.racfella-agent.rule=Host(`racfella-agent.racfathers.io`)
      - traefik.http.routers.racfella-agent.entrypoints=websecure
      - traefik.http.routers.racfella-agent.tls=true
      - traefik.http.routers.racfella-agent.tls.certresolver=le
      # Service (internal container port)
      - traefik.http.services.racfella-agent.loadbalancer.server.port=3000
      # Middlewares
      - traefik.http.middlewares.racfella-agent-compress.compress=true
      - traefik.http.middlewares.racfella-agent-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS
      - traefik.http.middlewares.racfella-agent-cors.headers.accesscontrolalloworigin=*
      - traefik.http.middlewares.racfella-agent-cors.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.racfella-agent-cors.headers.addvaryheader=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.racfella-agent.middlewares=racfella-agent-compress,racfella-agent-cors
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - proxy
      - racfella-internal
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  proxy:
    external: true
    name: proxy
  racfella-internal:
    driver: bridge
