services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: racfella-agent:latest
    container_name: racfellaagent
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      # point to the redis service on the same docker network
      # if you set REDIS_PASSWORD, also set REDIS_URL below to redis://:password@redis:6379
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}

      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:?Set OPENROUTER_API_KEY in your environment}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      MORALIS_API_KEY: ${MORALIS_API_KEY:-}
      ADVANCED_MODEL: ${ADVANCED_MODEL:-gpt-4-turbo-preview}
      UTILITY_MODEL: ${UTILITY_MODEL:-gpt-3.5-turbo}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-text-embedding-ada-002}
      AES_ENCRYPTION_KEY: ${AES_ENCRYPTION_KEY:?Set AES_ENCRYPTION_KEY in your environment}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:?Set TWILIO_ACCOUNT_SID in your environment}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:?Set TWILIO_AUTH_TOKEN in your environment}
      TWILIO_WHATSAPP_FROM: ${TWILIO_WHATSAPP_FROM:?Set TWILIO_WHATSAPP_FROM in your environment}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY:-}
      APP_BASE_URL: ${APP_BASE_URL:-https://racfella-agent.racfathers.io}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-https://racfella-agent.racfathers.io}
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # Router
      - traefik.http.routers.racfellaagent.rule=Host(`racfella-agent.racfathers.io`)
      - traefik.http.routers.racfellaagent.entrypoints=websecure
      - traefik.http.routers.racfellaagent.tls=true
      - traefik.http.routers.racfellaagent.tls.certresolver=le
      # Service (internal container port)
      - traefik.http.services.racfellaagent.loadbalancer.server.port=3000
      # Middlewares
      - traefik.http.middlewares.racfellaagent-compress.compress=true
      - traefik.http.routers.racfellaagent.middlewares=racfellaagent-compress
    networks:
      - proxy

  redis:
    image: redis:7-alpine
    container_name: racfella-redis
    restart: unless-stopped
    # If REDIS_PASSWORD is set in .env, this will add --requirepass
    command: >
      sh -lc 'exec redis-server --appendonly yes
      ${REDIS_PASSWORD:+ --requirepass ${REDIS_PASSWORD}}'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - proxy

volumes:
  redis_data:

networks:
  proxy:
    external: true
    name: proxy